const actionsMenu = {
    FETCH_DATA_MENU: 'FETCH_DATA_MENU',
    FETCH_DATA_MENU_SUCCESS: 'FETCH_DATA_MENU_SUCCESS',
    FETCH_DATA_MENU_FAILURE: 'FETCH_DATA_MENU_FAILURE',
    
    GET_MASTER: 'GET_MASTER',
    GET_MASTER_SUCCESS: 'GET_MASTER_SUCCESS',

    GET_MASTER_PRODUCT: 'GET_MASTER_PRODUCT',
    GET_MASTER_PRODUCT_SUCCESS: 'GET_MASTER_PRODUCT_SUCCESS',

    UPDATE_DATA_MENU: 'UPDATE_DATA_MENU',
    UPDATE_DATA_MENU_SUCCESS: 'UPDATE_DATA_MENU_SUCCESS',
};

export default actionsMenu;
