const actionBanner = {
    FETCH_BANNER_MASTER: 'FETCH_BANNER_MASTER',
    FETCH_BANNER_MASTER_SUCCESS: 'FETCH_BANNER_MASTER_SUCCESS',
    FETCH_BANNER_MASTER_FAILURE: 'FETCH_BANNER_MASTER_FAILURE',

    FETCH_BANNER_LIST: 'FETCH_BANNER_LIST',
    FETCH_BANNER_LIST_SUCCESS: 'FETCH_BANNER_LIST_SUCCESS',
    FETCH_BANNER_LIST_FAILURE: 'FETCH_BANNER_LIST_FAILURE',

    UPDATE_BANNER: 'UPDATE_BANNER',
    UPDATE_BANNER_SUCCESS: 'UPDATE_BANNER_SUCCESS',
    UPDATE_BANNER_FAILURE: 'UPDATE_BANNER_FAILURE',

    CREATE_BANNER: 'CREATE_BANNER',
    CREATE_BANNER_SUCCESS: 'CREATE_BANNER_SUCCESS',
    CREATE_BANNER_FAILURE: 'CREATE_BANNER_FAILURE',

    DELETE_BANNER: 'DELETE_BANNER',
    DELETE_BANNER_SUCCESS: 'DELETE_BANNER_SUCCESS',
    DELETE_BANNER_FAILURE: 'DELETE_BANNER_FAILURE',
};

export default actionBanner;
