const actionTableConfig={
    CHANGE_COLUMN_TABLE: "CHANGE_COLUMN_TABLE",
    CHANGE_COLUMN_TABLE_LOADING: "CHANGE_COLUMN_TABLE_LOADING",
    CHANGE_COLUMN_TABLE_SUCCESS: "CHANGE_COLUMN_TABLE_SUCCESS",
    CHANGE_COLUMN_TABLE_FAILED: "CHANGE_COLUMN_TABLE_FAILED",
    
    RESET_COLUMN_TABLE: "RESET_COLUMN_TABLE",
    RESET_COLUMN_TABLE_LOADING: "RESET_COLUMN_TABLE_LOADING",
    RESET_COLUMN_TABLE_SUCCESS: "RESET_COLUMN_TABLE_SUCCESS",
    RESET_COLUMN_TABLE_FAILED: "RESET_COLUMN_TABLE_FAILED",

    REQUEST_GET_COLUMN_TABLE: "REQUEST_GET_COLUMN_TABLE",
    REQUEST_GET_COLUMN_TABLE_LOADING: "REQUEST_GET_COLUMN_TABLE_LOADING",
    REQUEST_GET_COLUMN_TABLE_SUCCESS: "REQUEST_GET_COLUMN_TABLE_SUCCESS",
    REQUEST_GET_COLUMN_TABLE_FAILED: "REQUEST_GET_COLUMN_TABLE_FAILED",

    REQUEST_CHANGE_COLUMN_TABLE: "REQUEST_CHANGE_COLUMN_TABLE",
    REQUEST_CHANGE_COLUMN_TABLE_LOADING: "REQUEST_CHANGE_COLUMN_TABLE_LOADING",
    REQUEST_CHANGE_COLUMN_TABLE_SUCCESS: "REQUEST_CHANGE_COLUMN_TABLE_SUCCESS",
    REQUEST_CHANGE_COLUMN_TABLE_FAILED: "REQUEST_CHANGE_COLUMN_TABLE_FAILED",

    REQUEST_RESET_COLUMN_TABLE: "REQUEST_RESET_COLUMN_TABLE",
    REQUEST_RESET_COLUMN_TABLE_LOADING: "REQUEST_RESET_COLUMN_TABLE_LOADING",
    REQUEST_RESET_COLUMN_TABLE_SUCCESS: "REQUEST_RESET_COLUMN_TABLE_SUCCESS",
    REQUEST_RESET_COLUMN_TABLE_FAILED: "REQUEST_RESET_COLUMN_TABLE_FAILED",
}

export default actionTableConfig;