const actions = {
    FETCH_GUI_LIST: 'FETCH_GUI_LIST',
    FETCH_GUI_LIST_SUCCESS: 'FETCH_GUI_LIST_SUCCESS',
    FETCH_GUI_LIST_FAILURE: 'FETCH_GUI_LIST_FAILURE',

    CREATE_GUI: 'CREATE_GUI',
    CREATE_GUI_SUCCESS: 'CREATE_GUI_SUCCESS',
    CREATE_GUI_FAILURE: 'CREATE_GUI_FAILURE',

    UPDATE_GUI: 'UPDATE_GUI',
    UPDATE_GUI_SUCCESS: 'UPDATE_GUI_SUCCESS',
    UPDATE_GUI_FAILURE: 'UPDATE_GUI_FAILURE',

    DELETE_GUI: 'DELETE_GUI',
    DELETE_GUI_SUCCESS: 'DELETE_GUI_SUCCESS',
    DELETE_GUI_FAILURE: 'DELETE_GUI_FAILURE',
    
    FETCH_GUI: 'FETCH_GUI',
    FETCH_GUI_SUCCESS: 'FETCH_GUI_SUCCESS',
    FETCH_GUI_FAILURE: 'FETCH_GUI_FAILURE',
};

export default actions;
