const actionNotFoundImage = {
    FETCH_NOT_FOUND_IMAGE_LIST: 'FETCH_NOT_FOUND_IMAGE_LIST',
    FETCH_NOT_FOUND_IMAGE_LIST_SUCCESS: 'FETCH_NOT_FOUND_IMAGE_LIST_SUCCESS',
    FETCH_NOT_FOUND_IMAGE_LIST_FAILURE: 'FETCH_NOT_FOUND_IMAGE_LIST_FAILURE',

    UPDATE_NOT_FOUND_IMAGE: 'UPDATE_NOT_FOUND_IMAGE',
    UPDATE_NOT_FOUND_IMAGE_SUCCESS: 'UPDATE_NOT_FOUND_IMAGE_SUCCESS',
    UPDATE_NOT_FOUND_IMAGE_FAILURE: 'UPDATE_NOT_FOUND_IMAGE_FAILURE',
};

export default actionNotFoundImage;
