const actionCandidate = {
    FETCH_PROPOSED_LOCATION: 'FETCH_PROPOSED_LOCATION',
    FETCH_PROPOSED_LOCATION_SUCCESS: 'FETCH_PROPOSED_LOCATION_SUCCESS',
    FETCH_PROPOSED_LOCATION_FAILURE: 'FETCH_PROPOSED_LOCATION_FAILURE',

    FETCH_EMPLOYEES: 'FETCH_EMPLOYEES',
    FETCH_EMPLOYEES_SUCCESS: 'FETCH_EMPLOYEES_SUCCESS',
    FETCH_EMPLOYEES_FAILURE: 'FETCH_EMPLOYEES_FAILURE',

    FETCH_CANDIDATES_MASTER: 'FETCH_CANDIDATES_MASTER',
    FETCH_CANDIDATES_MASTER_SUCCESS: 'FETCH_CANDIDATES_MASTER_SUCCESS',
    FETCH_CANDIDATES_MASTER_FAILURE: 'FETCH_CANDIDATES_MASTER_FAILURE',

    GET_CANDIDATE_DETAIL: 'GET_CANDIDATE_DETAIL',
    LOADING_GET_CANDIDATE_DETAIL: 'LOADING_GET_CANDIDATE_DETAIL',
    GET_CANDIDATE_DETAIL_SUCCESS: 'GET_CANDIDATE_DETAIL_SUCCESS',
    GET_CANDIDATE_DETAIL_FAILURE: 'GET_CANDIDATE_DETAIL_FAILURE',

    FETCH_CANDIDATES_LIST: 'FETCH_CANDIDATES_LIST',
    FETCH_CANDIDATES_LIST_SUCCESS: 'FETCH_CANDIDATES_LIST_SUCCESS',
    FETCH_CANDIDATES_LIST_FAILURE: 'FETCH_CANDIDATES_LIST_FAILURE',

    CREATE_CANDIDATES: 'CREATE_CANDIDATES',
    CREATE_CANDIDATES_SUCCESS: 'CREATE_CANDIDATES_SUCCESS',
    CREATE_CANDIDATES_FAILED: 'CREATE_CANDIDATES_FAILED',

    UPDATE_CANDIDATES: 'UPDATE_CANDIDATES',
    UPDATE_CANDIDATES_SUCCESS: 'UPDATE_CANDIDATES_SUCCESS',
    UPDATE_CANDIDATES_FAILED: 'UPDATE_CANDIDATES_FAILED',

    DELETE_CANDIDATES: 'DELETE_CANDIDATES',
    DELETE_CANDIDATES_SUCCESS: 'DELETE_CANDIDATES_SUCCESS',
    DELETE_CANDIDATES_FAILED: 'DELETE_CANDIDATES_FAILED',

    CHANGE_STATUS_CANDIDATE: 'CHANGE_STATUS_CANDIDATE',
    CHANGE_STATUS_CANDIDATE_SUCCESS: 'CHANGE_STATUS_CANDIDATE_SUCCESS',
    CHANGE_STATUS_CANDIDATE_FAILED: 'CHANGE_STATUS_CANDIDATE_FAILED',

    GET_RECRUITMENT_BY_ID: 'GET_RECRUITMENT_BY_ID',
    GET_RECRUITMENT_BY_ID_SUCCESS: 'GET_RECRUITMENT_BY_ID_SUCCESS',
    GET_RECRUITMENT_BY_ID_FAILED: 'GET_RECRUITMENT_BY_ID_FAILED',
};

export default actionCandidate;
