const actions = {
    SUBMIT_LOGIN2: 'SUBMIT_LOGIN2',
    SUBMITING_LOGIN2: 'SUBMITING_LOGIN2',
    SUBMIT_LOGIN_SUCCESS2: 'SUBMIT_LOGIN_SUCCESS2',
    SUBMIT_LOGIN_FAILURE2: 'SUBMIT_LOGIN_FAILURE2',

    RESET_FORM_LOGIN2: 'RESET_FORM_LOGIN2',
    RESET_SIGN_IN2: 'RESET_SIGN_IN2',

};

export default actions;
