const actionsProduct = {
    FETCH_PRODUCT: 'FETCH_PRODUCT',
    FETCH_PRODUCT_SUCCESS: 'FETCH_PRODUCT_SUCCESS',
    FETCH_PRODUCT_FAILURE: 'FETCH_PRODUCT_FAILURE',

    UPDATE_PRODUCT: 'UPDATE_PRODUCT',
    UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
    UPDATE_PRODUCT_FAILURE: 'UPDATE_PRODUCT_FAILURE',

    SEARCH_PRODUCT_MORE: 'SEARCH_PRODUCT_MORE',
    SEARCH_PRODUCT_MORE_SUCCESS: 'SEARCH_PRODUCT_MORE_SUCCESS',
    SEARCH_PRODUCT_MORE_FAILURE: 'SEARCH_PRODUCT_MORE_FAILURE',
};

export default actionsProduct;
