const actionProsose = {
  FETCH_PROPOSED_LOCATION: "FETCH_PROPOSED_LOCATION",
  FETCH_PROPOSED_LOCATION_SUCCESS: "FETCH_PROPOSED_LOCATION_SUCCESS",
  FETCH_PROPOSED_LOCATION_FAILURE: "FETCH_PROPOSED_LOCATION_FAILURE",

  FETCH_PROPOSED_MASTER: "FETCH_PROPOSED_MASTER",
  FETCH_PROPOSED_MASTER_SUCCESS: "FETCH_PROPOSED_MASTER_SUCCESS",
  FETCH_PROPOSED_MASTER_FAILURE: "FETCH_PROPOSED_MASTER_FAILURE",

  FETCH_EMPLOYEE_LIST: "FETCH_EMPLOYEE_LIST",
  FETCH_EMPLOYEE_LIST_SUCCESS: "FETCH_EMPLOYEE_LIST_SUCCESS",
  FETCH_EMPLOYEE_LIST_FAILURE: "FETCH_EMPLOYEE_LIST_FAILURE",

  FETCH_POSITION_LIST: "FETCH_POSITION_LIST",
  FETCH_POSITION_LIST_SUCCESS: "FETCH_POSITION_LIST_SUCCESS",
  FETCH_POSITION_LIST_FAILURE: "FETCH_POSITION_LIST_FAILURE",

  GET_PROPOSE_DETAIL_START: "GET_PROPOSE_DETAIL_START",
  LOADING_GET_PROPOSE_DETAIL: "LOADING_GET_PROPOSE_DETAIL",
  GET_PROPOSE_DETAIL_START_SUCCESS: "GET_PROPOSE_DETAIL_START_SUCCESS",
  GET_PROPOSE_DETAIL_START_FAILURE: "GET_PROPOSE_DETAIL_START_FAILURE",

  FETCH_PROPOSED_LOCATION_LIST: "FETCH_PROPOSED_LOCATION_LIST",
  FETCH_PROPOSED_LOCATION_LIST_SUCCESS: "FETCH_PROPOSED_LOCATION_LIST_SUCCESS",
  FETCH_PROPOSED_LOCATION_LIST_FAILURE: "FETCH_PROPOSED_LOCATION_LIST_FAILURE",

  CREATE_PROPOSED_LOCATION: "CREATE_PROPOSED_LOCATION",
  CREATE_PROPOSED_LOCATION_SUCCESS: "CREATE_PROPOSED_LOCATION_SUCCESS",
  CREATE_PROPOSED_LOCATION_FAILED: "CREATE_PROPOSED_LOCATION_FAILED",

  UPDATE_PROPOSED_LOCATION: "UPDATE_PROPOSED_LOCATION",
  UPDATE_PROPOSED_LOCATION_SUCCESS: "UPDATE_PROPOSED_LOCATION_SUCCESS",
  UPDATE_PROPOSED_LOCATION_FAILED: "UPDATE_PROPOSED_LOCATION_FAILED",

  DELETE_PROPOSED_LOCATION: "DELETE_PROPOSED_LOCATION",
  DELETE_PROPOSED_LOCATION_SUCCESS: "DELETE_PROPOSED_LOCATION_SUCCESS",
  DELETE_PROPOSED_LOCATION_FAILED: "DELETE_PROPOSED_LOCATION_FAILED",

  CHANGE_STATUS_PROPOSE: "CHANGE_STATUS_PROPOSE",
  CHANGE_STATUS_PROPOSE_SUCCESS: "CHANGE_STATUS_PROPOSE_SUCCESS",
  CHANGE_STATUS_PROPOSE_FAILED: "CHANGE_STATUS_PROPOSE_FAILED",
};

export default actionProsose;
