const action = {
    SUBMIT_USER: 'SUBMIT_USER',
    SUBMITING_USER: 'SUBMITING_USER2',

    GET_USER_INFORMATION: 'GET_USER_INFORMATION',
    GET_USER_INFORMATION_SUCCESS: 'GET_USER_INFORMATION_SUCCESS',
    GET_USER_INFORMATION_FALIED: 'GET_USER_INFORMATION_FALIED',

    SUBMIT_LOGOUT: 'SUBMIT_LOGOUT',
    SUBMITTING_LOGOUT: 'SUBMITTING_LOGOUT',
    SUBMIT_LOGOUT_SUCCESS: 'SUBMIT_LOGOUT_SUCCESS',
    SUBMIT_LOGOUT_FAILURE: 'SUBMIT_LOGOUT_FAILURE',
}

export default action
